name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          # Here we pass the Cypress record key from the GitHub Secrets
          key: ${{ secrets.CYPRESS_RECORD_KEY }}
        # Set environment variables for Cypress
        env:
          # Ensure the CYPRESS_PROJECT_ID is stored in GitHub Secrets
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # Use the GitHub token secret for Cypress dashboard
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      # The default browser, if none is specified, is the built-in Electron browser.
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
